### ISSUE TITLE
Получать данные сразу в Map, а не парсить строку.

### ISSUE THREAD

**Issue by CrazyChris3310** [CrazyChris3310/ZigbeePolivalka#2]
https://github.com/CrazyChris3310/ZigbeePolivalka/blob/e5815faaad150b86e42302fb23a0ffb613f623ce/src/main/java/com/example/zigbeepolivalka/controllers/RequestController.java#L59-L61

**Comment by 1MikhailStepanov1** [comment]
Closed.
